# vnc_passwd: |
#   devops101

# vnc_view_passwd: |
#   devops202

# vnc_base_screen_res: 1300x700
# vnc_local_access_only: "yes"

# vnc_unix_user: ~
guac_path: /guacamole-docker-compose
guac_passwd: pommedeterre
