- name: template kubernetes teaching install script
  template:
    src: kubernetes.sh.j2
    dest: /opt/kubernetes.sh
    mode: 0777
# - name: execute template kubernetes teaching install script
#   shell: /opt/kubernetes.sh
