- name: Copy flavour install shell to disk
  template:
    src: flavour.sh.j2
    dest: /opt/flavour.sh
    mode: 0550


- name: template terraform install script
  template:
    src: terraform.sh.j2
    dest: /opt/terraform.sh
    mode: 0777

- name: template ansible install script
  template:
    src: ansible.sh.j2
    dest: /opt/ansible.sh
    mode: 0777

- name: template ansible install script
  template:
    src: kubernetes.sh.j2
    dest: /opt/kubernetes.sh
    mode: 0777

- name: template ansible lxd teaching install script
  template:
    src: "{{ item }}.j2"
    dest: /opt/{{ item }}
    mode: 0777
  loop:
    - lxd_config.yaml
    - lxd.sh


- name: run flavour install shell
  shell: /opt/flavour.sh

- name: run kubernetes install shell
  shell: /opt/kubernetes.sh

- name: Include Ansible teaching requirements tasks
  include_tasks: formation_ansible.yml
  when: formation_ansible
  tags: ["formation_ansible", "lxd_group"]

- name: Include kubernetes teaching requirements tasks
  include_tasks: formation_k8s.yml
  when: formation_k8s
  tags: ["formation_k8s"]
