- name: Copy flavour install shell to disk
  template:
    src: flavour.sh.j2
    dest: /opt/flavour.sh
    mode: 0550


- name: run flavour install shell
  shell: /opt/flavour.sh

- name: template terraform install script
  template:
    src: terraform.sh.j2
    dest: /opt/terraform.sh
    mode: 0777

- name: template ansible install script
  template:
    src: ansible.sh.j2
    dest: /opt/ansible.sh
    mode: 0777

- name: template ansible lxd teaching install script
  template:
    src: "{{ item }}.j2"
    dest: /opt/{{ item }}
    mode: 0777
  loop:
    - lxd_config.yaml
    - lxd.sh


