apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guacamole
  namespace: argo-cd
spec:
  destination:
    namespace: guacamole
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.beryju.io 
    chart: guacamole
    targetRevision: 1.4.0
    helm:
      values: |
        ingress:
          enabled: true
          hosts:
            - host: guacamole.formation.eliegavoty.xyz
              paths: 
                - "/"
          tls:
            - secretName: chart-example-tls
              hosts:
                - guacamole.formation.eliegavoty.xyz
          annotations:
            kubernetes.io/tls-acme: "true"
            cert-manager.io/cluster-issuer: letsencrypt-prod