apiVersion: v1
kind: Namespace
metadata:
  name: guacamole
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argo-cd
spec:
  destination:
    namespace: guacamole
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 12.2.0
    helm:
      values: |
        auth:
          username: guacamole
          password: password
          postgresPassword: password
          database: guacamole