base_user_password: ilovegit
allow_passwd_ssh_connection: "yes"
ssh_public_key: ~

ansible_user: root

## Which environment to setup
formation_ansible: no
formation_k8s: no

kubectl_state: absent
docker_state: present
lxd_state: present
