base_user_password: devops101
allow_passwd_ssh_connection: "yes"
ssh_public_key: ~

ansible_user: root

## Which environment to setup
formation_ansible: yes
formation_k8s: no

kubectl_state: absent
docker_state: absent 
lxd_state: absent
