base_user_password: devops101
allow_passwd_ssh_connection: "yes"
ssh_public_key: ~

ansible_user: root

## Which environment to setup
formation_ansible: no
formation_k8s: yes

kubectl_state: present
docker_state: present
lxd_state: absent
