ansible_user: root

base_unix_user: stagiaire
base_user_password: pommedeterre
allow_passwd_ssh_connection: "yes"
ssh_public_key: ~/Desktop/docker-humancoders.pub

vnc_unix_user: stagiaire
vnc_local_access_only: "no"
vnc_base_screen_res: 1300x700
