- name: Restart Guacamole
# - name: Restart Guacamole docker compose
  community.docker.docker_compose:
    project_src: "{{ guac_path }}"
    state: present
    restarted: yes

- name: Restart Guacamole container only
  community.docker.docker_compose:
    project_src: "{{ guac_path }}"
    services:
      - guacamole_compose
    state: present
    restarted: yes

- name: Restart guacamole nginx
  community.docker.docker_compose:
    project_src: "{{ guac_path }}"
    services:
      - nginx-proxy
      - letsencrypt
    state: present
    restarted: yes
