---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance
    image: docker.io/pycontribs/debian:latest
    pre_build_image: true
provisioner:
  name: ansible
