- name: Apt update, upgrade and install utils
  apt:
    upgrade: "yes"
    update_cache: yes

# - name: Enable and configure ufw firewall
#   ufw:
#     state: disabled
#     policy: allow

- name: Ensure docker repo present
  git:
    dest: "{{ guac_path }}"
    repo: https://github.com/boschkundendienst/guacamole-docker-compose.git # required. git, SSH, or HTTP(S) protocol address of the git repository.
    update: no
  tags: guac_install
  register: guac_code

- name: Ensure vnc servers are configured
  template:
    dest: "{{ guac_path }}/docker-compose.yml" # required. Location to render the template to on the remote machine.
    src: docker-compose.yml.j2
  tags: guac_install
  register: docker_code

- name: set guac_just_installed var
  ansible.builtin.set_fact:
    guac_just_installed: "{{ guac_code.changed or docker_code.changed }}"
  tags: guac_install

- name: Prepare guacamole server
  command: ./prepare.sh
  args:
    chdir: "{{ guac_path }}"
  when: guac_just_installed
  tags: guac_install

- name: Ensure vnc servers are configured
  template:
    # /etc/guacamole in the guacamole docker container
    dest: "{{ guac_path }}/user-mapping.xml" # required. Location to render the template to on the remote machine.
    src: user-mapping.xml.j2
  tags: guac_config

- name: Ensure docker-compose guacamole is started
  community.general.docker_compose:
    project_src: "{{ guac_path }}"
    # recreate: always
    # started: yes
    restarted: yes
    # register: output
  tags: guac_config

- name: Add user-mapping.xml file
  shell: "docker cp {{ guac_path }}/user-mapping.xml guacamole_compose:/root/.guacamole/user-mapping.xml"
  tags: guac_config

- name: Ensure guacamole_compose is restarted with config file
  community.general.docker_compose:
    services: guacamole_compose
    project_src: "{{ guac_path }}"
    restarted: yes
    # register: output
  tags: guac_config
