- hosts: guacamole_servers
  become: yes
  # strategy: free

  roles:
    - name: uptime.docker_setup
      vars:
        docker_users:
          - "{{ base_unix_user }}"
    - name: uptime.guacamole_setup
