- hosts: k3s_cluster
  become: yes
  roles:
    - name: xanmanning.k3s
      tags:
       - k3s_cluster

- hosts: localhost
  tasks:
    - name: Slurp k3s_kubeconfig
      slurp:
        src: /etc/rancher/k3s/k3s.yaml
      delegate_to: "{{ groups['k3s_server'][0] }}"
      register: k3s_kubeconfig
      no_log: true
      tags:
       - k3s_cluster

    - name: write k3s kubeconfig locally
      copy:
        content: "{{ k3s_kubeconfig['content'] | b64decode | replace('127.0.0.1', hostvars[groups['k3s_server'][0]].ansible_host) }}"
        dest: ~/.kube/guac3s.kubeconfig
      no_log: true
      tags:
       - k3s_cluster
