---

- name: configure ufw to authorize guacamole_servers.ansible_host
  hosts: vnc_servers
  become: yes
  strategy: free

  # pre_tasks:
  #   - name: Policy allow
  #     community.general.ufw:
  #       state: enabled
  #       policy: allow

  #   - name: Allow VNC 5901 access from guacamole ip (has priority)
  #     community.general.ufw:
  #       rule: allow
  #       port: '5901'
  #       from_ip: "{{ hostvars['guacamole-server']['ansible_host'] }}"
  #       to_ip: any

  #   - name: Deny VNC 5901 access (default rule for ips other than guacamole's one)
  #     community.general.ufw:
  #       rule: deny
  #       port: '5901'
  #       to_ip: any

  pre_tasks:
    - name: Policy allow
      community.general.ufw:
        state: enabled
        policy: allow

    - name: Allow VNC 5901 access from guacamole ip (has priority)
      community.general.ufw:
        rule: allow
        port: '5901'
        from_ip: "{{ hostvars['guacamole-server']['ansible_host'] }}"
        to_ip: any
    
    - name: Allow VNC 5901 access from guacamole wireguard ip (has priority)
      community.general.ufw:
        rule: allow
        port: '5901'
        from_ip: "{{ hostvars['guacamole-server']['vpn_ip'] }}"
        to_ip: any

    - name: Deny VNC 5901 access (default rule for ips other than guacamole's one)
      community.general.ufw:
        rule: deny
        port: '5901'
        to_ip: any

  roles:
    - role: ufw_manage
