- hosts: vnc_servers
  become: yes
  strategy: free

  # pre_tasks:
  #   - name: Policy allow
  #     community.general.ufw:
  #       state: enabled
  #       policy: allow

  #   - name: Allow VNC 5901 access from guacamole ip (has priority)
  #     community.general.ufw:
  #       rule: allow
  #       port: '5901'
  #       from_ip: "{{ hostvars['guacamole-server']['ansible_host'] }}"
  #       to_ip: any

  #   - name: Deny VNC 5901 access (default rule for ips other than guacamole's one)
  #     community.general.ufw:
  #       rule: deny
  #       port: '5901'
  #       to_ip: any

  roles:
    - name: uptime.tigervnc_setup
      tags: ["tigervnc_setup"]

    - name: uptime.dev_env_setup
      tags: ["dev_env_setup"]

    - name: uptime.docker_setup
      vars:
        docker_users:
          - "{{ base_unix_user }}"
      when: docker_state == "present"

    - name: ufw_manage
