- hosts: vnc_servers
  tasks:
    - name: Ensure xrdp package is present
      apt:
        name: xrdp
        state: present
      tags: ["xrdp"]

    - name: add xsession config
      lineinfile:
        path: /home/{{ vnc_unix_user }}/.xsession
        line: "xfce4-session"
        create: yes
      tags: ["xrdp"]

    # See URL :
    - name : add file to avoid the error message on startup
      copy :
        content : |-
            [Allow Colord all Users]
            Identity=unix-user:*
            Action=org.freedesktop.color-manager.create-device;org.freedesktop.color-manager.create-profile;org.freedesktop.color-manager.delete-device;org.freedesktop.color-manager.delete-profile;org.freedesktop.color-manager.modify-device;org.freedesktop.color-manager.modify-profile
            ResultAny=no
            ResultInactive=no
            ResultActive=yes
        dest:  /etc/polkit-1/localauthority/50-local.d/ 45-allow-colord.pkla
      tags: [ "xrdp" ]

    - name: add ssl-cert group
      group:
        name: ssl-cert
      tags: ["xrdp"]

    - name: add xrdp user to ssl-cert group
      user:
        name: xrdp
        groups: ssl-cert
        append: yes
      tags: ["xrdp"]

    - name: restart xrdp service
      systemd:
        name: xrdp
        state: restarted
      tags: ["xrdp"]

    - name: Add {{ base_unix_user }} user and add it to sudo group
      user:
        name: "{{ base_unix_user }}"
        groups: ["docker"]
        append: yes