- name: Ensure XFCE config folder exists
  file:
    path: "/home/{{ vnc_unix_user }}/.config/xfce4/xfconf/xfce-perchannel-xml/"
    state: directory
    recurse: yes

- name: Set Xfce panel config for a simple panel on the bottom
  template:
    src: xfce4-panel.xml.j2
    dest: /home/{{ vnc_unix_user }}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml
    owner: "{{ vnc_unix_user }}"

- name: Set Xfce desktop background to solid color
  template:
    src: xfce4-desktop.xml.j2
    dest: /home/{{ vnc_unix_user }}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
    owner: "{{ vnc_unix_user }}"

- name: Set Xfce WM config to switch workspace number to one 
  template:
    src: xfwm4.xml.j2
    dest: /home/{{ vnc_unix_user }}/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml
    owner: "{{ vnc_unix_user }}"

- name: Set Xfce theme to greybird dark
  template:
    src: xsettings.xml.j2
    dest: /home/{{ vnc_unix_user }}/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml
    owner: "{{ vnc_unix_user }}"

- name: Disable light-locker to avoid blank screens after a while
  lineinfile:
      path: /etc/xdg/autostart/light-locker.desktop
      line: Hidden=true

<<<<<<< HEAD
- name: Ensure correct rights in home directory
  file:
    path: "/home/{{ vnc_unix_user }}/.config"
    state: directory
    recurse: yes
    owner: "{{ vnc_unix_user }}"

- name: Ensure correct rights in home directory
  file:
    path: "/home/{{ vnc_unix_user }}/.ssh"
    state: directory
    recurse: yes
    owner: "{{ vnc_unix_user }}"

- name: Ensure correct rights in home directory
  file:
    path: "/home/{{ vnc_unix_user }}/.xsession"
    state: file
    owner: "{{ vnc_unix_user }}"

# - name: Restart vncserver
#   systemd:
#     name: xrdp
#     state: restarted
#     daemon_reload: yes
#     enabled: yes
=======
- name: Restart vncserver
  systemd:
    name: vncserver@:1
    state: restarted
    daemon_reload: yes
    enabled: yes
>>>>>>> parent of 007f1be (big refacto update WIP)
