- name: Upgrade packages
  apt:
    update_cache: yes
    upgrade: "yes"

- name: Ensure we have firefox installed
  apt:
    name: firefox
    state: "{{ firefox_state }}"

- name: Ensure we have snap installed
  apt:
    name: snapd
    state: present

- name: Ensure we have vscode installed
  snap:
    name: code
    state: "{{ vscode_state }}"
    classic: yes

# TODO: Add VScode to "open with" menu with Thunar

- name: Fix some snap/vscode bug by first collecting user id for user {{ base_unix_user }}
  shell: id --user {{ base_unix_user }}
  register: user_id

- name: Fix some snap/vscode bug by ensuring /run/user/{{ user_id.stdout }} is owned by user {{ base_unix_user }}
  file:
    path: "/run/user/{{ user_id.stdout }}"
    state: "directory"
    mode: "0700"
    owner: "{{ base_unix_user }}"
    recurse: true

- name: Ensure we have LXD installed if required, but don't uninstall it
  snap:
    name: lxd
    state: "{{ lxd_state }}"
  when: lxd_state == "present"

- name: Ensure we have kubectl installed or not
  snap:
    name: kubectl
    state: "{{ kubectl_state }}"
    classic: yes
 
# - name: Ensure we have Lens required library installed
#   apt:
#     name: libxss1
#     state: "{{ lens_state }}"


# TODO: snap not working, needs AppImage instead
#  - name: Ensure we have Lens installed
#   snap:
#     name: kontena-lens
#     state: present

