- name: Upgrade servers
  apt:
    update_cache: yes
    upgrade: "yes"

- name: Ensure we have firefox installed
  apt:
    name: firefox
    state: "{{ firefox_state }}"

- name: Ensure we have thonny+img tools installed
  apt:
    name:
      - thonny
      - krita
      - python3-pil #(install pillow fork)
      - eog #(for pil show)
    state: "present"

- name: Add repo and install vscode using shell apt 
  shell:
    cmd: |
      curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
      install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
      echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list
      apt update
      apt install code
      touch /root/vscode_install_flag
    creates: /root/vscode_install_flag
    executable: /bin/bash

- name: Ensure we have snap installed
  apt:
    name: snapd
    state: present

# - name: Fix some snap/vscode bug by first collecting user id for user {{ base_unix_user }}
#   shell: id --user {{ base_unix_user }}
#   register: user_id

# - name: Fix some snap/vscode bug by ensuring /run/user/{{ user_id.stdout }} is owned by user {{ base_unix_user }}
#   file:
#     path: "/run/user/{{ user_id.stdout }}"
#     state: "directory"
#     owner: "{{ base_unix_user }}"

- name: Ensure we have LXD installed or not
  snap:
    name: lxd
    state: "{{ lxd_state }}"

- name: Ensure we have kubectl installed or not
  snap:
    name: kubectl
    state: "{{ kubectl_state }}"
    classic: yes

- name: Include Ansible teaching requirements tasks
  include_tasks: formation_ansible.yml
  when: formation_ansible
  tags: ["formation_ansible", "lxd_group"]
  
 
