- name: Upgrade servers
  apt:
    update_cache: yes
    upgrade: "yes"

- name: Ensure we have firefox installed
  apt:
    name: firefox
    state: "{{ firefox_state }}"

- name: Ensure we have snap installed
  apt:
    name: snapd
    state: present

- name: Ensure we have vscode installed
  snap:
    name: code
    state: "{{ vscode_state }}"
    classic: yes

- name: Fix some snap/vscode bug by first collecting user id for user {{ base_unix_user }}
  shell: id --user {{ base_unix_user }}
  register: user_id

- name: Fix some snap/vscode bug by ensuring /run/user/{{ user_id.stdout }} is owned by user {{ base_unix_user }}
  file:
    path: "/run/user/{{ user_id.stdout }}"
    state: "directory"
    owner: "{{ base_unix_user }}"

- name: Ensure we have LXD installed
  snap:
    name: lxd
    state: "{{ lxd_state }}"

- name: Ensure we have kubectl installed
  snap:
    name: kubectl
    state: "{{ kubectl_state }}"
    classic: yes
 
