---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: formations-quiz-instance
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    privileged: true
    command: /lib/systemd/systemd
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
  inventory:
    host_vars:
      formations-quiz-instance:
        formations_quiz_student_user: molecule_student
verifier:
  name: ansible
