- hosts: all
  become: yes
  tasks:
    - name: Display all variables/facts known for a host
      debug:
        var: hostvars[inventory_hostname]
      tags: debug_info
  roles:
    - name: ubu_server_prepare
  vars:
    base_user_password: pommedeterre
    base_unix_user: stagiaire
    allow_passwd_ssh_connection: yes
    ssh_public_key: ~/Desktop/docker-humancoders.pub
  tags: setup_servers

- hosts: vnc_servers
  become: yes

  roles:
    - name: tigervnc_setup
  tags: setup_vnc

- hosts: guacamole_servers
  become: yes
  pre_tasks:
    - name: install pip3
      apt:
        name:
          - python3-pip
    - name: add docker python sdk
      pip:
        executable: pip3
        name:
          - docker
          - docker-compose
    # - name: Install docker-compose
    #   command: sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    #   args:
    #     creates: /usr/local/bin/docker-compose
  roles:
    - name: geerlingguy.docker
    - name: guacamole_setup
  vars:
    docker_install_compose: true
    docker_compose_version: "1.26.0"
    docker_compose_path: /usr/local/bin/docker-compose
  tags: setup_guac
