- hosts: all
  name: wait for ssh
  gather_facts: false
  tasks:
    - wait_for:
        port: 22
        host: '{{ ansible_host }}'
      delegate_to: localhost

- import_playbook: playbooks/deb_server_prepare.yml
- import_playbook: playbooks/xrdp.yml
- import_playbook: playbooks/customize_xfce_vnc.yml
- import_playbook: playbooks/k3s.yml
- import_playbook: playbooks/bootstrap_cluster.yml
- import_playbook: playbooks/install_guacamole_k8s.yml
- import_playbook: playbooks/install_scripts.yml
