- name: Apt update, upgrade and install utils
  apt:
    upgrade: "yes"
    update_cache: yes

# - name: Enable and configure ufw firewall
#   ufw:
#     state: disabled
#     policy: allow

- name: Ensure some utils are present
  apt:
    pkg:
      - htop
      - vim

- name: Ensure xubuntu-desktop is present
  apt:
    name:
      - xubuntu-desktop

- name: Ensure tigervnc server and plugins are present
  apt:
    name:
      - tigervnc-standalone-server
      - tigervnc-xorg-extension
      # - tigervnc-viewer

- name: Ensure password is configured
  # with vncpasswd -f the password has to end with \n
  # moreover to generate a view password concat a second binary passwd to the first one
  shell: |
    mkdir -p /home/{{ vnc_unix_user }}/.vnc
    # set -o pipefail
    echo {{ vnc_passwd }} | vncpasswd -f > /home/{{ vnc_unix_user }}/.vnc/passwd
    # vncpasswd -f {{ vnc_passwd }} > /home/{{ vnc_unix_user }}/.vnc/passwd
  # args:
  #   creates: /home/{{ base_unix_user }}/.vnc/passwd
  become: yes
  become_user: stagiaire
  tags: vnc_passwd

# Alternative from https://github.com/shellbro/ansible-role-vnc-server/blob/master/tasks/main.yml:
# shell: |
#   set -o pipefail
#   echo {{ password }} | vncpasswd -f > /home/{{ user }}/.vnc/passwd

# alternative from https://cplatform99.blogspot.com/2017/05/vnc-configuration-using-ansible-in.html
#   - name: "Generate vnc password for root user remotely"
#     shell: |
#         echo RedHat123 | vncpasswd -f > /root/.vnc/passwd

- name: Ensure view password is configured
  # moreover to generate a view password concat a second binary passwd to the first one
  shell: |
    # mkdir -p /home/{{ vnc_unix_user }}/.vnc
    vncpasswd -f {{ vnc_view_passwd }} >> /home/{{ vnc_unix_user }}/.vnc/passwd
  # args:
  #   creates: /home/{{ base_unix_user }}/.vnc/passwd
  become: yes
  become_user: stagiaire
  tags: vnc_passwd
  when: vnc_view_passwd is defined

- name: Ensure xstartup config exist
  template:
    src: xstartup.j2
    dest: /home/{{ vnc_unix_user }}/.vnc/xstartup
  become: yes
  become_user: stagiaire
  tags: chown

- name: Ensure vncserver service exist
  template:
    src: vncserver.service.j2
    dest: /etc/systemd/system/vncserver@.service
  tags: chown

- name: Ensure vncserver service is enabled and started on screen :1 and port 5901
  systemd:
    name: vncserver@:1
    state: restarted
    daemon_reload: yes
    enabled: yes
  tags: chown
